server:
  port: 8080
jwt:
  access-expired-time: 3600000
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  access-token-name: access-token

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(V41cnySNYg4LBlI3zwPp6EA3Q+pMlTt5kBRLgzNcgE9ghcq04lqim4TUsUoS/OU8t36xZsVhx+BmGUb04SBNnlpXArkoPkG7X9yGTFxo5yGPiVHltX7hLU7dOwSFMKrIjaIoAOEAuqWNfqZNj1AexA==)
    username: root
    password: ENC(Ul3QA3fCcxjukvjLMBqZyagnH/14kpod)

  api:
    naver-sms-service-id: ncp:sms:kr:296262910669:lis-project
    naver-sms-access-key: YoVm5953mBJcYIycnAU8
    naver-sms-secret-key: fwUbvEheldNf6t5zlXrHaIm3UjejExNBokf3Fmaj
    naver-caller-line: 01046766654

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml