server:
  port: 8080
jwt:
  access-expired-time: 3600000
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  access-token-name: access-token

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(EfItFCbCkrqIz2vfhxts8UT+MkkiE6KL6rYCC/o1UmiaiPKp9h173gxAHVHocHvBoubog9V8j1bcCfk6ZH+xhr/v67lQtKZAMMf8pKMYKjshRbEHNfxobIm/n3e6XLk0UsiVGRvWSUGJMzdNK0WPQV7qFpHlg1IF)
    username: root
    password: ENC(Ul3QA3fCcxjukvjLMBqZyagnH/14kpod)

  api:
    naver-sms-service-id: ncp:sms:kr:296262910669:lis-project
    naver-sms-access-key: YoVm5953mBJcYIycnAU8
    naver-sms-secret-key: fwUbvEheldNf6t5zlXrHaIm3UjejExNBokf3Fmaj
    naver-caller-line: 01046766654

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework: DEBUG
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml